server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/leyou?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
      #data-password: 123456   一定不要粗心写成这个鬼东西
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #让mybatis输出sql语句
